"""Fill the [[PLACEHOLDER]] slots in submission/SUBMISSION.md from measured results.

Numbers in a submission should never be typed by hand -- that is exactly how a figure
drifts out of sync with the artifact and torches the credibility of every other number
on the page. Anything we could not measure is written as "not measured".
"""
import json, re, sys
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
metrics = {r["name"]: r for r in json.loads((ROOT / "results/metrics.json").read_text())}
bench_p = ROOT / "serve/artifacts/benchmark.json"
bench = json.loads(bench_p.read_text()) if bench_p.exists() else {}
url = (ROOT / "serve/artifacts/PUBLIC_URL").read_text().strip() if (ROOT / "serve/artifacts/PUBLIC_URL").exists() else "<live-url>"

NM = "not measured"
def m(name, slice_="overall", key="map@25", fmt="{:.3f}"):
    r = metrics.get(name)
    if not r or not r["metrics"].get(slice_):
        return NM
    return fmt.format(r["metrics"][slice_][key])

def first(names, **kw):
    for n in names:
        v = m(n, **kw)
        if v != NM:
            return v
    return NM

final = ["shipped_onnx_full:test", "biencoder_r3_hardneg:test", "biencoder_r2_synth:test"]
n_synth = NM
fp = ROOT / "results/synth_filter_report.json"
if fp.exists():
    n_synth = f"{json.loads(fp.read_text())['kept']:,}"

cost_rows = {r["name"]: r for r in bench.get("cost", {}).get("rows", [])}
ours = next((r for r in cost_rows.values() if r.get("shipped")), None)
frontier = next((r for r in cost_rows.values() if not r.get("shipped")), None)
ratio = NM
for h in bench.get("headline", []):
    if "cheaper" in h.get("key", ""):
        ratio = h["value"].rstrip("x")

teacher = m("teacher7b:test")
shipped = first(final)
gap = NM
if teacher != NM and shipped != NM:
    gap = f"{float(teacher) - float(shipped):.3f}"

vals = {
    "N_SYNTH": n_synth,
    "R25_UNSEEN_BEFORE": m("biencoder_r1_realonly:test", "unseen", "recall@25"),
    "R25_UNSEEN_AFTER": first(["biencoder_r3_hardneg:test", "biencoder_r2_synth:test"],
                              slice_="unseen", key="recall@25"),
    "MAP_FINAL": shipped,
    "MAP_FLOOR": m("offtheshelf:bge-small-en-v1.5"),
    "P50": str(bench.get("latency", {}).get("p50", NM)),
    "COST_OURS": ours["per_1k"] if ours else NM,
    "COST_FRONTIER": frontier["per_1k"] if frontier else NM,
    "COST_RATIO": ratio,
    "DISTILL_GAP": gap,
    "URL": url,
}
# ---- regenerate the README results table from measured metrics ----
README_ROWS = [
    ("Off-the-shelf `bge-small` (33M, no training)", "offtheshelf:bge-small-en-v1.5"),
    ("Off-the-shelf `bge-m3` (568M, no training)", "offtheshelf:bge-m3"),
    ("General 7B, zero-shot rerank (no task training)", "llm7b_zeroshot_rerank:test"),
    ("Fine-tuned retriever, real data only", "biencoder_r1_realonly:test"),
    ("+ synthetic, naive 1:6.6 mix", "biencoder_r2_synth:test"),
    ("+ hard-negative mining", "biencoder_r3_hardneg:test"),
    ("+ real data oversampled 6x **(selected on val)**", "biencoder_r3_rr6:test"),
    ("7B LoRA reranker (teacher, never deployed)", "teacher7b:test"),
    ("**WhyWrong shipped** (22M student, INT8 ONNX, CPU)", "shipped_onnx_full:test"),
]
lines = ["| System | MAP@25 | Recall@25 | R@25 unseen | Top-1 |",
         "|---|---|---|---|---|"]
for label, key in README_ROWS:
    if key not in metrics:
        continue
    lines.append(f"| {label} | {m(key)} | {m(key, key='recall@25')} | "
                 f"{m(key, 'unseen', 'recall@25')} | {m(key, key='top1_acc')} |")
table_md = "\n".join(lines)
rp = ROOT / "README.md"
rs = rp.read_text()
rs = re.sub(r"<!-- RESULTS:BEGIN.*?-->.*?<!-- RESULTS:END -->",
            "<!-- RESULTS:BEGIN (generated by scripts/12_fill_submission.py -- do not edit by hand) -->\n"
            + table_md + "\n<!-- RESULTS:END -->", rs, flags=re.S)
rp.write_text(rs)
print(f"README results table: {len(lines)-2} rows written")

src = (ROOT / "submission/SUBMISSION.md").read_text()
out = re.sub(r"\[\[(\w+)\]\]", lambda x: vals.get(x.group(1), NM), src)
(ROOT / "submission/SUBMISSION_FILLED.md").write_text(out)
print(json.dumps(vals, indent=2))
missing = [k for k, v in vals.items() if v == NM]
print(f"\n-> submission/SUBMISSION_FILLED.md")
if missing:
    print(f"STILL UNMEASURED: {', '.join(missing)}")
